services:
  db:
    image: postgres:16
    container_name: mywiki_db
    restart: always
    env_file: .env  # Загружаем переменные из .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mywiki_backend
    restart: always
    env_file: .env  # Загружаем переменные в FastAPI
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
