FROM sphinxdoc/sphinx:8.1.3 AS build

WORKDIR /docs
COPY . /docs

RUN pip3 install --upgrade \
    myst-parser \
    sphinx-book-theme \
    sphinx-design \
    linkify-it-py \
    sphinxcontrib-plantuml \
    sphinx-copybutton \
    setuptools \
    /docs/localextensions/sphinxcontrib-images \
    /docs/localextensions/example-plate


RUN make clean html

FROM nginx:1.27

EXPOSE 80

COPY --from=build /docs/build/html /usr/share/nginx/html
